services:
  mongo:
    image: mongo:7
    container_name: food-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network


  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    restart: unless-stopped
    networks:
      - app-network

  kafka-setup:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-setup
    depends_on:
      - kafka
    networks:
      - app-network
    command: >
      bash -c "
        echo 'Ожидание запуска Kafka...'
        cub kafka-ready -b kafka:29092 1 40
        echo 'Создание топиков...'
        kafka-topics --create --if-not-exists --topic object-created-topic --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
        kafka-topics --create --if-not-exists --topic confirmation-topic --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
        echo 'Топики успешно созданы!'
      "

  foodservice1:
    build:
      context: .
      dockerfile: ./first_microserv.dockerfile
    container_name: FoodService
    ports:
      - "7210:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
      MongoDbSettings__DatabaseName: "FoodDB1"
      Kafka__BootstrapServers: "kafka:29092"
    restart: unless-stopped
    depends_on:
      kafka-setup:
        condition: service_completed_successfully
      mongo:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - app-network

  user-service:
    build:
      context: ./UserService
      dockerfile: User.dockerfile
    container_name: User-Service
    ports:
      - "7211:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
      Kafka__BootstrapServers: "kafka:29092"
    restart: unless-stopped
    depends_on:
      kafka-setup:
        condition: service_completed_successfully
      mongo:
        condition: service_started
    networks:
      - app-network
  
  prometheus:
    image: prom/prometheus:latest
    container_name: food-prometheus
    depends_on:
      - foodservice1
      - user-service
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    ports:
      - "9090:9090"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: food-redis
    ports:
      - "6380:6379"
    networks:
      - app-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: food-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network

volumes:
  mongo_data:
  prometheus_data:
  grafana_data:
  redis_data:

networks:
  app-network:
    driver: bridge