services:
  mongo:
    image: mongo:7
    container_name: food-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_CREATE_TOPICS: "object-created-topic:1:1,confirmation-topic:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped
    networks:
      - app-network


  foodservice1:
    build:
      context: .
      dockerfile: ./first_microserv.dockerfile
    container_name: FoodService
    ports:
      - "7210:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
      MongoDbSettings__DatabaseName: "FoodDB1"
      Kafka__BootstrapServers: "kafka:29092"
    restart: unless-stopped
    depends_on:
      - redis
      - mongo
    networks:
      - app-network

  user-service:
    build:
      context: ./UserService
      dockerfile: User.dockerfile
    container_name: User-Service
    depends_on:
      - mongo
    ports:
      - "7211:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
      Kafka__BootstrapServers: "kafka:9092"
    restart: unless-stopped
    networks:
      - app-network
  
  prometheus:
    image: prom/prometheus:latest
    container_name: food-prometheus
    depends_on:
      - foodservice1
      - user-service
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    ports:
      - "9090:9090"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: food-redis
    ports:
      - "6380:6379"
    networks:
      - app-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: food-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network

volumes:
  mongo_data:
  prometheus_data:
  grafana_data:
  redis_data:

networks:
  app-network:
    driver: bridge