services:
  mongo:
    image: mongo:7
    container_name: food-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "object-created-topic:1:1,confirmation-topic:1:1"
    ports:
      - "9092:9092"
    restart: unless-stopped
    networks:
      - app-network

  
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERCONNECT: 'kafka:9092'
      JVM_OPTS: "-Xms32M -Xmx64M"
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
       - app-network
       
  prometheus:
    image: prom/prometheus:latest
    container_name: food-prometheus
    depends_on:
      - foodservice1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    ports:
      - "9090:9090"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: food-redis
    ports:
       - "6380:6379"
    networks:
       - app-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: food-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network


  foodservice1:
    build:
      context: .
      dockerfile: ./first_microserv.dockerfile
    container_name: FoodService
    ports:
      - "7210:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"  
      MongoDbSettings__ConnectionString: "mongodb://admin:password@mongo:27017"
      MongoDbSettings__DatabaseName: "FoodDB1" 
      Kafka__BootstrapServers: "kafka:9092"
    restart: unless-stopped
    networks:
      - app-network
    
  user-service:
    build:
      context: ./UserService
      dockerfile: User.dockerfile

    container_name: food-user-service

    depends_on:
      - mongo
      - kafka

    ports:
      - "7212:8080"

    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__MongoDb: "mongodb://admin:password@mongo:27017"
      Kafka__BootstrapServers: "kafka:9092"

    restart: unless-stopped

    networks:
      - app-network

volumes:
  mongo_data:
  prometheus_data:
  grafana_data:
  redis_data:

networks:
  app-network:
    driver: bridge